server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    druid:

      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver

      url: jdbc:mysql://codekitty.cn:3306/communitymyblog?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: root
      password: lihaiyang

      initial-size: 1
      min-idle: 1
      max-active: 20

      max-wait: 60000

      time-between-eviction-runs-millis: 60000

      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

mybatis:
  type-aliases-package: cn.codekitty.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml